[package]
name = "rusaint-cli"
version.workspace = true
authors = ["JOONGGON LEE <2wndrhs@gmail.com>", "Hyomin Koo <me@eatsteak.dev>"]
description = "CLI for fetching course schedules"
repository = "https://github.com/eatsteak/rusaint"
readme = "README.md"
license.workspace = true
edition.workspace = true

[dependencies]
rusaint = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
thiserror = { workspace = true }
clap = { version = "4.5.27", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15.7"
