[package]
name = "rusaint"
description = "Easy-to-use SSU u-saint client"
categories = ["web-programming"]

version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
readme.workspace = true

[features]
default = ["application", "element"]
element = ["dep:scraper"]
application = ["element"]
uniffi = ["dep:uniffi", "application"]

[dependencies]
uniffi = { workspace = true, optional = true }
derive_builder = "0.20.2"
reqwest = { version = "0.13.2", features = [
    "charset",
    "http2",
    "rustls",
    "cookies",
    "gzip",
    "brotli",
], default-features = false }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
html-escape = "0.2.13"
url = "2.5.4"
roxmltree = "0.21.0"
lol_html = "2.3.0"
scraper = { version = "0.25", features = ["atomic"], optional = true }
serde = { version = "1", features = ["derive"] }
custom_debug_derive = "0.6.2"
regex-lite = "0.1.6"
serde_json = "1.0.140"
reqwest_cookie_store = { version = "0.10.0", features = ["serde"] }
cookie_store = "0.22"
tracing = "0.1.41"
wdpe = { version = "0.4.1", features = ["reqwest"] }
ozra = { version = "0.0.1" }

[dev-dependencies]
anyhow = "1"
dotenvy = "0.15.7"
futures = "0.3.31"
tokio-test = "0.4.4"
tokio = { workspace = true, features = ["macros", "test-util"] }
lazy_static = "1.5.0"
tracing-test = "0.2.5"

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[lints]
workspace = true
