[package]
name = "rusaint"
description = "Easy-to-use SSU u-saint client"
categories = ["web-programming"]

version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
readme.workspace = true

[features]
default = ["application", "element"]
element = ["dep:scraper"]
application = ["element"]
uniffi = ["dep:uniffi", "application"]

[dependencies]
uniffi = { version = "0.29.0", optional = true }
derive_builder = "0.20.2"
reqwest = { version = "0.12.9", features = [
    "charset",
    "http2",
    "macos-system-configuration",
    "rustls-tls",
    "cookies",
    "gzip",
    "brotli",
], default-features = false }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
html-escape = "0.2.13"
url = "2.5.4"
roxmltree = "0.20.0"
lol_html = "2.1.0"
scraper = { version = "0.23.1", features = ["atomic"], optional = true }
serde = { version = "1", features = ["derive"] }
custom_debug_derive = "0.6.1"
regex-lite = "0.1.6"
log = { version = "0.4.22", features = ["kv"] }
serde_json = "1.0.140"


[dev-dependencies]
anyhow = "1"
dotenv = "0.15.0"
futures = "0.3.30"
tokio-test = "0.4.4"
tokio = { workspace = true, features = ["macros", "test-util"] }
lazy_static = "1.5.0"
pretty_env_logger = "0.5.0"
test-log = "0.2.17"

[build-dependencies]
uniffi = { version = "0.29.0", features = ["build"] }
